### ISSUE TITLE
Defining the scope of the conference

### ISSUE THREAD

**Issue by gilligan** [gilligan/ramdaconf#2]
Even though I picked the name `ramdaconf` I suppose that the scope should be `Functional Programming in Javascript` ? What do others think ?

**Comment by jethrolarson** [comment]
Ramda's tagine is _practical functional js_, so I guess that's roughly the domain.

**Comment by CrossEye** [comment]
I agree.  And if we end up dropping the name to be more inclusive that's fine.

**Comment by gilligan** [comment]
Alright - well I will say anything that fits within `functional programming in javascript` will do.
