### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by stoeffel** [gilligan/ramdaconf#4]
Does ramdaconf even need sponsors?
How do we find sponsors?
Does anyone want to be a sponsor?

**Comment by jethrolarson** [comment]
What costs do we anticipate?

**Comment by gilligan** [comment]
Only if whatever we pick for streaming was not for free?

**Comment by gilligan** [comment]
If there was a need for some $$$ I think I could get my company to sponsor it. Right now I do not see the need.
