### ISSUE TITLE
Possible Attendees

### ISSUE THREAD

**Issue by CrossEye** [gilligan/ramdaconf#5]
Leave a comment if you think you'd be interested in attending (given that we don't know _any_ details yet.)  Please include your timezone to help us with scheduling.

See also [Possible Presenters](https://github.com/gilligan/ramdaconf/issues/6).

**Comment by CrossEye** [comment]
I'd be interested in attending.  I'm on U.S. East Coast time, GMT-5.

**Comment by jethrolarson** [comment]
+1 PST -0800

**Comment by stoeffel** [comment]
:+1: UTC+1 Switzerland

**Comment by svozza** [comment]
:+1: GMT London

**Comment by Avaq** [comment]
:wave: Me!
:clock1: GMT+1

**Comment by davidchambers** [comment]
:+1: PST

**Comment by megawac** [comment]
+1, EST

**Comment by boxofrox** [comment]
:+1: EST (GMT-5)

**Comment by nsluss** [comment]
- 1 PST

**Comment by joneshf** [comment]
:+1: PST

**Comment by kwijibo** [comment]
GMT

**Comment by jasonbellamy** [comment]
I would love to attend something like this.

EST (GMT-5)

**Comment by benperez** [comment]
[America/Los_Angeles](https://en.wikipedia.org/wiki/America/Los_Angeles)

**Comment by ghost** [comment]
Count me in! Same time zone as @benperez

**Comment by yurrriq** [comment]
Into it. -6.

**Comment by buzzdecafe** [comment]
EST GMT - 5

**Comment by sebinsua** [comment]
GMT.

As long as it's not on at 3am in my timezone I'd join...

**Comment by wmrowan** [comment]
America/Los_Angeles

**Comment by lo1tuma** [comment]
:+1: GMT +01:00

**Comment by aychtang** [comment]
GMT + 1

**Comment by kibin** [comment]
GMT +3 or +1, depends on when the conference is going to be

**Comment by rockymadden** [comment]
GMT -7 (MTN)

**Comment by ikr** [comment]
GMT+1

**Comment by bsonntag** [comment]
:+1: GMT

**Comment by mfirry** [comment]
GMT+1

**Comment by gilligan** [comment]
Thanks everyone. I conclude that there is interest :) As for the time this will have to be chosen according to those presenting I suppose. I will try to find the best option but of course it can never be perfect for everyone.
