### ISSUE TITLE
Decide for a name

### ISSUE THREAD

**Issue by gilligan** [gilligan/ramdaconf#7]
So on the one hand I ♥️ Ramda and would thus be tempted to stick to ramdaconf- on the other hand it is certainly not going to be limited to Ramda. Any other suggestions?

**Comment by davidchambers** [comment]
I think ramdaconf (or RamdaConf) is a good name. Ramda is a library, of course, but more importantly it has brought together a group of curious, helpful, like-minded programmers who've built other principled libraries which play nicely in the Ramda ecosystem.

**Comment by joneshf** [comment]
I think it's a good name.

**Comment by ghost** [comment]
Seconding what @davidchambers said. ramdaconf is perfect!

**Comment by gilligan** [comment]
So since nobody is screaming in protest lets stick with ramdaconf.

**Comment by davidchambers** [comment]
@gilligan, is the canonical capitalization "ramdaconf"? Works for me, I just want to know how to write it. :)

**Comment by CrossEye** [comment]
Save the pinkies!  "ramdaconf" is so much easier to type!  :smile:
